docs_dir: documentation
repo_url: https://github.com/norm/flourish/
site_author: Mark Norman Francis
site_name: Flourish
theme: readthedocs

pages:
    - Getting started:
        - What is Flourish?: index.markdown
        - How Flourish works: how-flourish-works.markdown
        - Installing: installing.markdown
        - The example site: example-site.markdown
    - Using flourish:
        - Adding sources: adding-sources.markdown
        - Generating the site: generating-the-site.markdown
        - Adding paths: adding-paths.markdown
        - Generating the HTML: generating-html.markdown
        - Template variables: template-variables.markdown
        - Template functions: template-functions.markdown
        - Template filters: template-filters.markdown
        - Site configuration: site-configuration.markdown
        - Adding assets: adding-assets.markdown
    - Advanced usage:
        - Linking sources together: linking-sources.markdown
    - Recipes:
        - Adding Atom (RSS) feeds: cookbook/atom-feeds.markdown
        - Date-based navigation: cookbook/date-based-navigation.markdown
        - Copyright year range: cookbook/publication-year-range.markdown
    - Hosting your site:
        - Uploading to Amazon S3: uploading-to-s3.markdown
    - Flourish API:
        - flourish: api-flourish.markdown
        - flourish.sourcelist: api-flourish-sourcelist.markdown
        - flourish.generators: api-flourish-generators.markdown
        - flourish.generators.base.BaseGenerator: api-flourish-generators-base.markdown
        - flourish.generators.base.SourceGenerator: api-flourish-generators-source.markdown
        - flourish.generators.base.IndexGenerator: api-flourish-generators-index.markdown
        - flourish.generators.base.PaginatedIndexGenerator: api-flourish-generators-paginatedindex.markdown
        - flourish.generators.base.AtomGenerator: api-flourish-generators-atom.markdown
        - flourish.generators.base.SassGenerator: api-flourish-generators-sass.markdown
        - flourish.generators.calendar.CalendarGenerator: api-flourish-generators-calendar.markdown
        - flourish.helpers: api-flourish-helpers.markdown
        - flourish.paginator: api-flourish-paginator.markdown
    - Release notes: release-notes.markdown

extra_css:
    - overrides.css
