docs_dir: documentation
repo_url: https://github.com/norm/flourish/
site_author: Mark Norman Francis
site_name: Flourish
theme: readthedocs

pages:
    - Getting started:
        - What is Flourish?: index.markdown
        - How Flourish works: how-flourish-works.markdown
        - Installing: installing.markdown
    - Using flourish:
        - Adding sources: adding-sources.markdown
        - Generating the site: generating-the-site.markdown
        - Adding URLs: adding-urls.markdown
        - Generating the HTML: generating-html.markdown
        - Site configuration: site-configuration.markdown
        - Adding assets: adding-assets.markdown
    - Recipes:
        - Adding Atom (RSS) feeds: atom-feeds.markdown
    - Flourish API:
        - flourish: api-flourish.markdown
        - flourish.generators: api-flourish-generators.markdown
        - flourish.generators.BaseGenerator: api-flourish-generators-base.markdown
        - flourish.generators.PageGenerator: api-flourish-generators-page.markdown
        - flourish.generators.IndexGenerator: api-flourish-generators-index.markdown
        - flourish.generators.PaginatedIndexGenerator: api-flourish-generators-paginatedindex.markdown
        - flourish.generators.AtomGenerator: api-flourish-generators-atom.markdown
        - flourish.paginator: api-flourish-paginator.markdown

extra_css:
    - overrides.css
